---
title: "Self-talk interventions and sport/motor performance: An updated systematic review and Bayesian meta-analysis"
author: "Hannah Corcoran, James Steele"
format: pdf
abstract: "Self-talk has been researched as an aspect of mental preparation for performance in sports and other motor tasks since the late 1980s. In 2011 Hatzigeorgiadis and colleagues systematically reviewed and meta-analysed three decades of self-talk intervention research including 32 studies. Yet, despite the general proliferation of meta-analyses, this topic has not been meta-analysed in the decade since their review which, at least for the main effect, provided a reasonably precise standardised mean difference estimate (0.48 [95% confidence interval: 0.38, 0.58]). Several further studies on self-talk interventions have been conducted in that time and it is of interest to explore what additional evidence they offer regarding the effects of self-talk interventions on sport/motor performance. Bayesian approaches are well positioned to explore how additional evidence changes our understanding of an effect; to see whether it has changed in sign, magnitude, or precision, or whether further research has largely been a ‘waste’. Therefore, our aim was to conduct an updated systematic review and Bayesian meta-analysis replicating the search, inclusion, and models of Hatzigeorgiadis et al. Informative priors were taken directly from Hatzigeorgiadis et al. A total of 28 studies were included in the final updated meta-analysis. The overall posterior pooled estimate for the standardised mean difference was almost exactly the same as the prior (mean: 0.46 [95% quantile interval: 0.38, 0.59]). Bayes factors were calculated for a range of effect sizes and indicated that the included studies largely reflected ‘weak’ evidence against effects ranging from ~0.3 to 0.7, and only provided ‘substantial’ evidence or greater against more extreme effects (either very small or very large). Results were largely similar for all moderator analyses which were updated too; either providing relatively weak evidence against effects found in the previous meta-analysis or evidence suggesting smaller effects for certain moderators. The findings of our updated Bayesian meta-analyses reiterate the positive effect of self-talk interventions on sport/motor performance. However, they also suggest that cumulatively the past decade and more of research has done little to further our understanding of these effects. Considering the limited resources and time for conducting research, it may be worth moving onto to other more pertinent questions regarding psychological interventions for sport/motor performance."
editor: 
  markdown: 
    wrap: sentence
---

<!-- Notes: Hatzigeorgiadis et al meta Focused on various aspects of task, self-talk, participants, and intervention... also explored "matching hypothesis" -->

<!-- Hardy et al - reflections paper Focus on measurement? -->

<!-- Should we also conduct a moderator analysis of studies doing manipulation checks and measurement of self-talk? -->

<!-- Other moderators? -->

<!-- Pressure? -->

<!-- Attention? -->

<!-- Interaction of population and type of self talk (instructional/motivational)? -->

<!-- Focus the review atheoretically? -->

<!-- Examining the effect of self-talk interventions -->

<!-- Add impact on attentional focus outcomes? -->

# Introduction

Self-talk has a long history of philosophical, theoretical, and empirical work [@geurtsMakingSenseSelf2018; @brinthauptSelftalkResearchChallenges2023; @latinjakSelfTalkInterdisciplinaryReview2023].
One area in which self-talk remains a popular topic of research up to this day is in the sport sciences [@vanraalteSelftalkReviewSportspecific2016; @hardyReflectionsMaturingResearch2018; @latinjakSelfTalkInterdisciplinaryReview2023].
Sport psychology as a broad field has focused on the theorising of psychological constructs that might impact upon performance, and the subsequent experimental testing of theoretically informed interventions to address these constructs.
For example, a recent umbrella review identified thirty meta-analyses exploring the effects of different sport psychology constructs upon performance, thirteen of them examining the effects of interventions, finding an overall standardised mean effect for positive constructs of 0.51 \[95% confidence interval: 0.42, 0.58\] [@lochbaumSportPsychologyPerformance2022].
Only one meta-analysis explored the effects of self-talk interventions; Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011].

The meta-analysis by Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011] included a total of 32 studies and 62 effect size estimates revealing an overall standardised mean difference estimate of 0.48 \[95% confidence interval: 0.38, 0.58\] and also explored the effects of various moderators of the effectiveness of self-talk interventions.
Around the time that Hatzigeorgiadis et al. conducted their meta-analysis the quantitative synthesis of research findings using meta-analytic tools was still relatively new in the sport sciences [@haggerMetaanalysisSportExercise2006].
However in the last decade, particularly in sport psychology, there has been an increasing reliance on meta-analyses [@lochbaumSportPsychologyPerformance2022; @haggerMetaanalysis2022].
Yet, despite the general proliferation of meta-analyses in the past decade, the effects of self-talk interventions has not been re-evaluated by means of such quantitative synthesis since 2011 when Hatzigeorgiadis et al. completed their work.
During this period though, empirical research regarding self-talk interventions for sport and motor performance has burgeoned leading some to reflect on the field as "maturing" post-2011 [@hardyReflectionsMaturingResearch2018].

Whilst self-talk as a field may have matured in the post-2011 years with theoretical advancements in conceptualisation of the construct and mediators of its effects on performance, efforts to improve operationalisation/measurement, and efforts to improve methodology used in studying self-talk [@brinthauptSelftalkResearchChallenges2023; @geurtsMakingSenseSelf2018; @hardyReflectionsMaturingResearch2018; @latinjakSelfTalkInterdisciplinaryReview2023; @vanraalteSelftalkReviewSportspecific2016] it could be argued that understanding of the effectiveness of self-talk interventions was "mature" prior to 2011.
The effect estimate from the meta-analysis of Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011] was already fairly precise, and indeed so to where many of the moderator estimates.
Several further studies on self-talk interventions have been conducted since 2011 and it is a reasonable question to ask, given the limited time and resource for conducting research in the field of sport science, to whether and to what extent these have advanced our understanding or whether they have largely contributed to "research waste".

Two questions that should (though arguably are not often enough particularly in sport science) be asked by researchers when planning a study of an experimental intervention is "what is the likelihood that the experimental intervention is superior to the control intervention given the evidence accumulated so far?" and "what is the likelihood that a new trial, given some design parameters and previous evidence, will demonstrate the superiority of the experimental intervention?".
The key here is to consider the *cumulative* nature of evidence provided by research.
Cumulative meta-analyses were proposed in the early 1990s and have since then been argued to be key tools to answering these questions and considering whether or not additional research is a worthwhile use of resources [@clarkeAccumulatingResearchSystematic2014; @graingerEvidenceSynthesisTackling2020] and Bayesian approaches are well positioned to tackle this [@biauUsingBayesianStatistics2017].
Within Bayesian statistical inference a prior probability distribution regarding the effect of interest is *updated* after the introduction of new evidence to a posterior probability distribution given Bayes theorem.

Given that there has not been, to the best of our knowledge, a meta-analytic synthesis of the effects of self-talk interventions effects upon sport/motor performance since Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011] it is unclear the extent to which the past decade and more of research has advanced our understanding or potentially contributed to research waste.
Therefore, our aim was to conduct an updated systematic review and Bayesian meta-analysis replicating the search, inclusion, and models of Hatzigeorgiadis et al.


# Method
The method for this systematic review and meta-analysis was adapted from Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011]. We extended their previous research by following the Preferred Reporting Items for Systematic reviews and Meta-analysis (PRISMA) guidelines [@pagePRISMA2020Statement2021]. We limited our searches to the date range of November 2011 to November 2023 to avoid double counting as we used the estimates from Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011] as informative priors in our meta-analyses which contain the information from studies prior to November 2011.

## Criteria for including studies
Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011] did not explicitly state a process or strategy to formulating their research question and search methods. However, we assume that the PICO (Participants, Intervention, Comparator and Outcome) framework was implicitly used and, with that assumption, we adopted the following inclusion criteria based on their description. Participants were healthy and of any performance level. The intervention was instruction to engage in positive self-talk[^1]. The comparator was no self-talk or unrelated self-talk. Outcomes were sport or motor task performance. We included both between and within group experimental designs with either pre-post, or post-only measurements of performance as well as within group pre-post trials. 

[^1]: Hatzigeorgiadis et al. [-@hatzigeorgiadisSelfTalkSportsPerformance2011] stated: *"As our purpose was to test the effectiveness of interventions aiming to improve performance, groups or conditions using negative ... or inappropriate self-talk ... were excluded. In addition, groups or conditions using assisted self-talk ... were also excluded as assisted self-talk involves the use of external aids, such as headphones, and was not considered pure self-talk intervention."*








## Search strategy
Studies were obtained through electronic journal searches and review articles along with personal communication. The following databases – Sport Discus, PsycINFO, PsycARTICLES and Medline – were selected through the EBSCO database to search for the keywords. The SCOPUS database was not used as it was not accessible through Solent University. Boolean commands of AND and OR were used with the keywords. These keywords were searched in the format of, with the application of the Boolean commands, self-talk OR self-instruction OR self-statements OR self-verbalizations OR verbal cues OR stimulus cueing OR thought content instructions AND sport OR performance OR motor performance OR task performance. The studies were all peer-reviewed, full text and published in English language journals. The search was limited to the date range of November 2011-November 2022. The search took place from October 2022-November 2022. An ethics statement was not required for this study. Zotero software was used for referencing and to manage the bibliography (Zotero 2022).

## Selection of studies
The PRISMA flow diagram was used to show a clear layout of the systematic review process. Studies were identified by searching the keywords (stated in the search strategy) in the databases (stated in the search strategy). Those studies were then downloaded into Covidence, a screening programme, where duplicates were removed (Covidence 2022). The remaining studies were screened by their title and abstract to see if they met the requirements of the inclusion criteria. Once that was completed, those studies were exported into excel as comma-separated values (csv). This showed that if any studies did not meet the criteria, they were removed. The next part of the screening phase consisted of assessing the full text of the studies for eligibility. This led to the final pool of studies that were assessed for inclusion in the review and meta-analysis.

## Data extraction
The data extracted from the studies were for all groups, all relevant groups in the study, pre and/or post intervention, means, sample sizes and either standard deviation, standard errors, variances or confidence intervals in order to calculate the effect sizes. The data extracted was imported into a spreadsheet in excel as a csv.

## Statistical analysis
Statistical analysis of the data extracted was performed in R, (v 4.0.2; R Core Team, https://www.r-project.org/). Studies were categorised by design (i.e., between-group, within-group and pre-post-group) and the means, sample sizes and either standard deviation, standard errors, variances or confidence intervals were extracted to calculate the standardised mean effect sizes in R. The standardised mean effect sizes were interpreted by using Cohen’s thresholds such that <0.2 to <0.5 is small, 0.5 to <0.8 is moderate and >0.8 is large (Cohen 2013). The standardised mean effect sizes were calculated such that a positive effect size value favoured self-talk improving sports performance. Given the inclusion of different study designs, the standardised mean effects were calculated appropriately according to their study design.
As the effect sizes calculated from the studies included had a nested structure (i.e., multiple effects nested within groups and nested within studies), and the intention to update Hatzigeorgiadis et al. (2011) study, a Bayesian multi-level meta-analysis was performed. The precision of the posterior estimates using 95% compatibility (confidence) intervals (CIs) were produced, weighted by the inverse sampling variance to account for the within- between and pre-post-study variance.
The Hatzigeorgiadis et al. (2011) study was also used as a prior by using its effect size. From the prior, a t-distribution and variance of 0.05 from the 95% CI was used and a degrees of freedom of 3. Furthermore, the posterior estimates of effect were calculated for each individual study and for the overall pooled estimate of the 95% CI. R-hat values, trace plots and posterior effects were examined to check the model fit and convergence.
